
ODOO_EMAIL=devops1@rg1.us
ODOO_PASSWORD=Devops123!!
ODOO_LOAD_DEMO_DATA=no
ODOO_SKIP_BOOTSTRAP=yes
POSTGRESQL_CLIENT_DATABASE_HOST=35.231.253.154
POSTGRESQL_CLIENT_DATABASE_PORT_NUMBER=5432
POSTGRESQL_CLIENT_DATABASE_ROOT_USER=postgres
POSTGRESQL_CLIENT_DATABASE_ROOT_PASSWORD=Y7C5SPjLhqmF
POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=odoo_5
POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=odoo    
POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=odoo

or

ODOO_SKIP_BOOTSTRAP=no
ODOO_DATABASE_HOST=35.231.253.154
ODOO_DATABASE_PORT_NUMBER=5432
ODOO_DATABASE_ADMIN_USER=bn_odoo
ODOO_DATABASE_PASSWORD=0676e3492c403b6653f8cd4a0a61facb085bbf5002a698a6ad1010917244ad00
ALLOW_EMPTY_PASSWORD=no


captainVersion: 4
networks:
    db:
        driver: bridge
    search:
        driver: bridge
services:
    #$$cap_appname-db:
        #image: postgres:$$cap_postgres_version
        #volumes:
            #- $$cap_appname-db-data:/var/lib/postgresql/data
        #restart: always
        #environment:
            #POSTGRES_USER: odoo
            #POSTGRES_PASSWORD: $$cap_postgres_password
            #POSTGRES_DB: postgres
        #caproverExtra:
            #notExposeAsWebApp: 'true'
    $$cap_appname:
        image: bitnami/odoo:$$cap_odoo_version
        #depends_on:
            #- $$cap_appname-db
        volumes:
            - $$cap_appname-odoo-web-data:/var/lib/odoo
            - $$cap_appname-config:/etc/odoo
            - $$cap_appname-addons:/mnt/extra-addons
        restart: always
        environment:
            #POSTGRES_PASSWORD: $$cap_postgres_password
            #HOST: srv-captain--$$cap_appname-db        
            
            BITNAMI_APP_NAME: odoo
            ODOO_EMAIL: devops1@rg1.us
            ODOO_PASSWORD: Devops123!!
            ODOO_LOAD_DEMO_DATA: no
            ODOO_SKIP_BOOTSTRAP: yes
            ODOO_DATABASE_HOST: 35.231.253.154
            ODOO_DATABASE_PORT_NUMBER: 5432
            ODOO_DATABASE_NAME: bitnami_odoo
            ODOO_DATABASE_PASSWORD: 0676e3492c403b6653f8cd4a0a61facb085bbf5002a698a6ad1010917244ad00
            #- ALLOW_EMPTY_PASSWORD=
             
        caproverExtra:
            containerHttpPort: '8069'
caproverOneClickApp:
    variables:
        #- id: $$cap_postgres_version
          #label: Postgres Version
          #defaultValue: 9.6.18-alpine
          #description: Check out their docker page for the valid tags https://hub.docker.com/r/library/postgres/tags/
          #validRegex: /^([^\s^\/])+$/
        #- id: $$cap_postgres_password
          #label: Postgres Password
          #description: ''
          #validRegex: /.{1,}/
        - id: $$cap_odoo_version
          label: Odoo Version
          defaultValue: 'latest'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/odoo?tab=tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: Odoo is an open source product CRM
        end: Odoo is deployed and the dashboard is available from http://$$cap_appname.$$cap_root_domain.
    isOfficial: true
    description: Odoo, formerly known as OpenERP, is a suite of open-source business apps written in Python and released under the AGPL license.
    documentation: https://hub.docker.com/_/odoo?tab=description
